Implement core functionality
gemini-testing/stat-reporter pull request #3
Opened 2016-12-21 13:05 UTC by tormozz48

2016-12-21 14:06 UTC, tormozz48 commented on lib/config.js
> +const ENV_PREFIX = 'brostatit_';
Заменить на актуальное название плагина

2016-12-21 14:06 UTC, tormozz48 commented on lib/config.js
> +const DEFAULT_REPORTER_HTML_PATH = 'brostatit.html';
Заменить на актуальное название плагина

2016-12-22 06:50 UTC, sipayRT requested changes

2016-12-22 06:50 UTC, sipayRT commented on lib/index.js
> +    subscribe(event, handler) {
давай переименуем на `on` или `subscribeOn`

2016-12-22 06:50 UTC, sipayRT commented on lib/config.js
> +            defaultValue: false,
почему false? гораздо удобнее использовать эту опцию только в случаях, когда плагин нужно отключить

2016-12-22 06:50 UTC, sipayRT commented on lib/config.js
> +    options = _.defaultsDeep(options, getDefaults());
я чет не понял зачем нам звать `getDefaults()`, если ты и так ниже опциям указываешь дефолтные значения

2016-12-22 06:50 UTC, sipayRT commented on gemini.js
> +        .subscribe(events.WARNING, function(data) {
разве у нас это событие где-то кидается?

2016-12-22 06:50 UTC, sipayRT commented on lib/model.js
> +    addFailed(browserId) {
предлагаю `addPassed`, `addSkipped` и `addFailed` обьединить в `addTestResult(browserId, result)`

2016-12-22 06:50 UTC, sipayRT commented on lib/model.js
> +    addFailed(browserId) {
но это такое...

2016-12-22 06:50 UTC, sipayRT commented on lib/model.js
> +            this._stat.set(browserId, _.values(FIELDS).reduce((acc, type) => _.set(acc, type, 0), {}));
а че не просто `acc[type] = 0;`? :)

2016-12-22 06:50 UTC, sipayRT commented on lib/model.js
> +    startBrowserTime(browserId) {
давай тут тогда тоже `mark` - методы, отмечающие начало и конец времени, должны быть похожи

2016-12-22 06:50 UTC, sipayRT commented on lib/config.js
> +const configParser = require('gemini-configparser');
а нам тут точно нужен конфиг-парсер? вроде и без него обойтись можно - опций не так много

2016-12-22 08:21 UTC, tormozz48 commented on lib/config.js
> +const configParser = require('gemini-configparser');
Тут самая писечка в том, что конфиг парсер позволяет переопределять настройки плагинов с помощью переменных окружения. По-другому это сделать нельзя.

А нам точно понадобится разное поведение на локальной машине и в sandbox например.

2016-12-22 08:21 UTC, tormozz48 commented on lib/config.js
> +    options = _.defaultsDeep(options, getDefaults());
Да, думаю что здесь ты прав.

2016-12-22 08:22 UTC, tormozz48 commented on gemini.js
> +        .subscribe(events.WARNING, function(data) {
Ну вот в gemini-report я увидел такую штуку

2016-12-22 08:22 UTC, tormozz48 commented on lib/model.js
> +    startBrowserTime(browserId) {
ок

2016-12-22 08:23 UTC, tormozz48 commented on lib/model.js
> +    addFailed(browserId) {
Спорное предложение. Мой вариант более явный

2016-12-22 08:24 UTC, tormozz48 commented on lib/model.js
> +            this._stat.set(browserId, _.values(FIELDS).reduce((acc, type) => _.set(acc, type, 0), {}));
Потому что `_.set` возвращает объект, что позволяет записать `reduce` одной строкой

2016-12-22 10:00 UTC, rostik404 commented on lib/model.js
> +        const browserData = this._findOrCreate(browserId);
Мне не очень нравится название функции - `findOrCreate`. Я бы как-то вроде `getBrowserData` назвал.

2016-12-22 10:01 UTC, rostik404 commented on lib/model.js
> +        const browserData = this._findOrCreate(browserId);
И еще, неудобно код читать, когда функция `_findOrCreate` в самом конце, а не сразу после ее использования.
Я понимаю, что ты приватные функции решил засунуть в конец, но я бы все таки в порядке использования в коде их группировал.

2016-12-22 10:09 UTC, rostik404 commented on lib/model.js
> +        const calculateDuration = (value) => {
Может сделать эту фукнцию статической приватной функцией класса, а не объявлять ее внутри другой функции?

2016-12-22 10:21 UTC, rostik404 commented on test/lib/config.js
> +            process.env.brostatit_enabled = true;
Тут по-другому наверное переменная называться будет? :)

2016-12-22 10:21 UTC, rostik404 commented on test/lib/config.js
> +            process.env.brostatit_enabled = true;
И все остальные переменные среды - тоже

2016-12-22 10:36 UTC, rostik404 commented on test/lib/index.js
> +        it('should use browserStat instance context in event handler', () => {
заменить `browserStat` на новое название

2016-12-22 10:40 UTC, rostik404 commented on lib/index.js
> +module.exports = class BrowserStat {
`StatReporter`?

2016-12-22 10:52 UTC, rostik404 commented on test/lib/model.js
> +    });
Два `describe` выше можно объединить с помощью `forEach`.

2016-12-22 10:58 UTC, rostik404 commented
Посмотрел

2016-12-22 14:26 UTC, sipayRT commented on gemini.js
> +        .subscribe(events.WARNING, function(data) {
думаю, это легаси. @eGavr ты ж вроде смотрел, что в gemini никто не слушает это событие

2016-12-24 07:43 UTC, tormozz48 commented on test/lib/model.js
> +    });
Можно, но ИМХО я считаю, что стоит по возможности избегать сложных структур таких как циклы тестов. Это по моему скромному мнению ухудшает понимание и читаемость тестов

2016-12-24 08:37 UTC, tormozz48 commented on lib/model.js
> +        const calculateDuration = (value) => {
Эта функция нужна исключительно в контексте расчета статистики.

2016-12-24 08:37 UTC, tormozz48 commented
@sipayRT @rostik404 @DudaGod Обновил

2016-12-25 14:00 UTC, j0tunn requested changes

2016-12-25 14:00 UTC, j0tunn commented on gemini.js
> +            this.model.markStartBrowserTime(data.id);
если выкинуть `StatReporter` как уровень абстракции, то все станет сильно проще:
```js
const model = new Model();

gemini
    .on(events.START_BROWSER, (browser) => model.markStartBrowserTime(brower.id))
    .on(events.STOP_BROWSER, (browser) => model.markEndBrowserTime(browser.id))
    ...
    .on(events. END_RUNNER, () => showStatistics(model));
```

2016-12-25 14:00 UTC, j0tunn commented on lib/model.js
> +module.exports = class Model {
`Model` - слишком абстрактное имя. Предлагаю переименовать в `Stat`, например

2016-12-25 14:00 UTC, j0tunn commented on lib/model.js
> +                ? value.timeEnd.getTime() - value.timeStart.getTime()
так может и сохранять сразу в секундах? `Date.now()`

2016-12-25 14:00 UTC, j0tunn commented on lib/model.js
> +        this._stat = new Map();
для чего `Map`?

2016-12-25 14:00 UTC, j0tunn commented on test/gemini.js
> +    gemini.events.END_RUNNER = 'endRunner';
```js
return _.extend(new QEmitter(), {
    events: {
        START_BROWSER: 'startBrowser',
        ...
    }
});
```
?

2016-12-25 14:00 UTC, j0tunn commented on test/lib/config.js
> +            /*eslint-disable */
а на что ругается `eslint`?

2016-12-25 19:58 UTC, tormozz48 commented on gemini.js
> +            this.model.markStartBrowserTime(data.id);
`StatReporter` по моей задумке это контроллер, который связывает между собой все модули плагина, а именно: модель, репортеры, конфиг. Кроме этого он предоставляет общее API для взаимодействия с gemini и hermione

2016-12-25 20:03 UTC, tormozz48 commented on lib/model.js
> +        this._stat = new Map();
Если ты подразумеваешь "почему ты не использовал объект для хранения структуры данных ключ-значение", то я стараюсь использовать средства языка которые были созданы специально для решения таких задач.

2016-12-25 20:05 UTC, tormozz48 commented on test/lib/config.js
> +            /*eslint-disable */
Свойства вида: `a_b_c`. Через нижнее подчеркивание

2016-12-25 20:07 UTC, tormozz48 commented on gemini.js
> +            this.model.markStartBrowserTime(data.id);
Другое дело, что `Model` можно было бы внести внутрь `StatReporter`

2016-12-25 21:03 UTC, j0tunn requested changes

2016-12-25 21:03 UTC, j0tunn commented on gemini.js
> +            this.model.markStartBrowserTime(data.id);
Ты переусложняешь:
- все, что здесь используется - это `this.model`, которая почему-то лежит в `StatReporter`, но используется здесь как автономный объект
- для того, чтобы снаружи был доступ к `model` ты сделал геттер
- `subscribeOn` - это вообще отдельная песня, обертка над `gemini.on`, который доступен здесь, но ты его вызываешь оттуда, и для того чтобы был доступ к той самой `model` нужно передавать `function`, которая будет биндиться на инстанс `StatReporter`, и внутри ты зовешь `this.model`. WAT?!

`StatReporter` можно тупо выбросить. [KISS](https://ru.wikipedia.org/wiki/KISS_(принцип))

А насчет MVC - не нужно использовать паттерн ради паттерна. Какую проблему ты пытаешься решить этим паттерном?

2016-12-25 21:03 UTC, j0tunn commented on lib/model.js
> +        this._stat = new Map();
> я стараюсь использовать средства языка которые были созданы специально для решения таких задач

Каких задач?
- тебе нужно знать размер мапы? Нет
- тебе нужно использовать в качестве ключей что-то кроме строк? Нет
- тебе нужно итерироваться по элементам в порядке вставки? Нет

Так для чего здесь `Map`?

2016-12-25 21:03 UTC, j0tunn commented on test/lib/config.js
> +            /*eslint-disable */
```js
process.env['stat_reporter_reporters_html_path'] = 'some/file/path.html';
```
?

2016-12-29 20:52 UTC, tormozz48 commented
@sipayRT @j0tunn Обновил

2017-01-09 16:02 UTC, sipayRT requested changes

2017-01-09 16:02 UTC, sipayRT commented on lib/stat.js
> +            this._stat.set(browserId, _.values(FIELDS).reduce((acc, type) => _.set(acc, type, 0), {}));
зачем каждый раз бегать редьюсом, если мы заранее знаем, что нам нужен объект из этих полей с нулевыми значениями? можно же заранее его один раз создать и им пользоваться как дефолтным значением

2017-01-09 16:02 UTC, sipayRT commented on lib/stat.js
> +        this._stat = new Map();
я понимаю, что круто, но не вижу тут необходимости использовать Map, а не простой объект

2017-01-09 16:02 UTC, sipayRT commented on lib/stat.js
> +            this._stat.set(browserId, _.values(FIELDS).reduce((acc, type) => _.set(acc, type, 0), {}));
и тут получится просто `this._stat[browserId] = defaultStat();` (или что-то типа того)

2017-01-09 16:02 UTC, sipayRT commented on test/gemini.js
> +    it('should add failed test on "TEST_RESULT" event with non-equal results', () => {
"with non-equal results" --> "on test fail"

2017-01-09 16:02 UTC, sipayRT commented on test/gemini.js
> +        assert.called(lib.showReport);
calledOnce

2017-01-09 16:02 UTC, sipayRT commented on test/gemini.js
> +        assert.called(lib.showReport);
не проверил с какими аргументами будет вызван метод

2017-01-09 16:02 UTC, sipayRT commented on test/lib/config.js
> +    describe('should enable plugin', () => {
вообще этими тестами ничего не проверяешь, т.к. у тебя по умолчанию эта опция `true`

2017-01-09 16:02 UTC, sipayRT commented on test/lib/reporters/index.js
> +
странно, что линтер не ругнулся на 2 пустых строки

2017-01-09 16:02 UTC, sipayRT commented on test/lib/reporters/index.js
> +            enabled: true,
эта опция здесь лишняя

2017-01-09 16:02 UTC, sipayRT commented on test/lib/stat.js
> +            model.markEndBrowserTime(browserId);
зачем здесь дергать `markEndBrowserTime`?

2017-01-09 16:02 UTC, sipayRT commented on test/lib/stat.js
> +        beforeEach(() => {
лучше это вынести в функцию

2017-01-10 15:46 UTC, tormozz48 commented on test/lib/reporters/index.js
> +
убрал пустую строку

2017-01-10 15:47 UTC, tormozz48 commented
@sipayRT Обновил

2017-01-10 15:57 UTC, tormozz48 commented on test/lib/stat.js
> +        beforeEach(() => {
Вынес

2017-01-10 19:38 UTC, tormozz48 commented
Так ладно. Вроде все кто хотел поревьюили а я честно исправил замечания. Вливаю, чтобы двигаться дальше

2017-01-10 19:45 UTC, merged