feat: Reporters Implementation
gemini-testing/stat-reporter pull request #4
Opened 2017-01-10 19:56 UTC by tormozz48

@DudaGod @rostik404 @sipayRT

2017-01-11 07:22 UTC, DudaGod requested changes

2017-01-11 07:22 UTC, DudaGod commented on lib/reporters/flat.js
> +const colums = () => [
colum**N**s?

2017-01-11 07:22 UTC, DudaGod commented on lib/reporters/html.js
> +    };
у тебя тут и в предыдущем файле повторяется список одних и тех же колонок. Может вынесем их в конфиг? Чтобы при изменении не нужно было править это в двух местах.

2017-01-11 07:22 UTC, DudaGod commented on lib/reporters/html.js
> +        /*eslint-enable */
не понял на что тут eslint ругается

2017-01-11 07:22 UTC, DudaGod commented on lib/util.js
> +exports.humanizeDuration = (duration) => {
может стоит тут как то указать, что `duration` ожидается в милисекундах (например переименовать переменную). Так как это не сразу очевидно.

2017-01-11 07:22 UTC, DudaGod commented on test/lib/reporters/flat.js
> +        sandbox.stub(console, 'info');
давай может, чтобы не стабать console - создадим в util.js `logger`, по типу как это у нас сделано в gemini?

2017-01-11 07:22 UTC, DudaGod commented on test/lib/reporters/flat.js
> +                duration: 987654
давай может тут `duration` укажем как 61000, тогда в тесте ниже получится - `1 min 1 sec`. Кажется это будет намного проще читать

2017-01-11 07:22 UTC, DudaGod commented on test/lib/reporters/flat.js
> +        });
я бы еще написал тест, что таблица не поехала никуда. То есть, кол-во столбцов в head, равно кол-ву столбцов в body

2017-01-11 07:22 UTC, DudaGod commented on test/lib/reporters/html.js
> +}
у тебя в предыдущем тестовом файле эта функция объявлена внутри дескрайб, а тут снаружи. Может давай сделаем консистентно? Мне больше нравится снаружи.

2017-01-11 07:22 UTC, DudaGod commented on test/lib/reporters/flat.js
> +        it('"failed" tests status if browser statistic has not failed tests', () => {
у тебя тут `not` лишний

2017-01-11 07:22 UTC, DudaGod commented on test/lib/reporters/html.js
> +        });
у тебя в этих тестах текст в `it` не соответствует проверяемому коду, т.е. перепутал местами

2017-01-11 07:22 UTC, DudaGod commented on test/lib/util.js
> +            sandbox.stub(console, 'error');
я тут тоже предлагаю `logger` заюзать

2017-01-11 08:32 UTC, rostik404 commented on lib/reporters/flat.js
> +const colums = () => [
А точно есть необходимость в том, чтобы делать из этого функцию, которая возвращает массив, а не оставить просто массив?

2017-01-11 08:37 UTC, rostik404 commented on lib/reporters/html.js
> +        /*eslint-enable */
Предполагаю, что на подчеркивание

2017-01-11 08:39 UTC, rostik404 commented on lib/reporters/html.js
> +        cellpadding: 5
По-моему, 0 и 5 на `magic numbers` похожи. Может в константы их вынести?

2017-01-11 08:41 UTC, rostik404 commented on lib/util.js
> +    const seconds = Math.floor((duration - minutes * MILLISECONDS_IN_MINUTE) / 1000);
А может для этих целей заюзать `moment` какой-нибудь?

2017-01-11 08:43 UTC, rostik404 commented on lib/util.js
> +exports.humanizeDuration = (duration) => {
`humanizeDuration` -> `stringifyDuration`?)

2017-01-11 08:45 UTC, rostik404 commented on lib/util.js
> +    const fileFullPath = path.join(process.cwd(), filePath);
а тут `path.resolve` не подойдет?

2017-01-11 08:46 UTC, rostik404 commented on lib/util.js
> +        fs.writeFileSync(fileFullPath, content, {encoding: 'utf-8'});
А почему не асинхронно?

2017-01-11 10:25 UTC, sipayRT requested changes
в репортерах есть много общей информацию, которую нужно вынести в отдельную прослойку, т.к. сейчас получается много дублирования

2017-01-11 10:25 UTC, sipayRT commented on lib/reporters/flat.js
> +const colums = () => [
а зачем ты ее функцией сделал? почему не просто массив?

2017-01-11 10:25 UTC, sipayRT commented on lib/reporters/flat.js
> +        head: colums().map((col) => chalk.white(col))
ну так тогда вроде ж можно просто 
```
{
    style: 
        {
            head: ['white']
        }
}
```
ну и красный цвет тоже норм - он же должен как-то отличаться от основного наполнения

2017-01-11 10:25 UTC, sipayRT commented on lib/reporters/html.js
> +    };
ну и хранить объект ради того, чтобы первая буква былы большой...

2017-01-11 10:25 UTC, sipayRT commented on lib/reporters/html.js
> +            broStat.duration = util.humanizeDuration(broStat.duration);
давай "человеческое" время записывать сразу при вычислении времени прохождения, чтобы потом в каждом репортере не выполнять одну и ту же информацию

2017-01-11 10:25 UTC, sipayRT commented on lib/reporters/html.js
> +        /*eslint-enable */
на подчеркивание

2017-01-11 10:25 UTC, sipayRT commented on lib/reporters/html.js
> +        /*eslint-disable */
только webStorm умеет так хреново комментировать строки. В конце пробел перед `*` есть ,а в начале - нет

2017-01-11 10:25 UTC, sipayRT commented on lib/reporters/html.js
> +        cellspacing: 0,
а бордеры по умолчанию рисуются?

2017-01-11 10:25 UTC, sipayRT commented on lib/reporters/html.js
> +        cellspacing: 0,
судя по доке, бордер рисуется по умолчанию, как и `cellspacing: 0`. Т.е. тебе это тут указывать не нужно

2017-01-11 10:25 UTC, sipayRT commented on lib/reporters/html.js
> +        header: _.keys(columns),
разве этот модуль не такой умный, что сам разберется какие ключи в шапке указать? или это для того, чтобы была четкая последовательность?

2017-01-11 10:25 UTC, sipayRT commented on lib/reporters/html.js
> +        header_mapping: columns,
давай просто в `header` укажем массив последовательности и все. никто не умрет :)

2017-01-11 10:25 UTC, sipayRT commented on lib/reporters/flat.js
> +        head: colums().map((col) => chalk.white(col))
или вообще 

```css
{
   css: 'thead {color: #fff;}'
}
```

2017-01-11 10:25 UTC, sipayRT commented on lib/reporters/html.js
> +    return `<!DOCTYPE html>
мож в одну строку? тут же обвязка не важна. Ну или массивом строк - у тебя их там не больше пяти должно получиться

2017-01-11 10:25 UTC, sipayRT commented on lib/reporters/html.js
> +    return `<!DOCTYPE html>
кстати, а не было либы, которая умеет сразу и обвязку построить?

2017-01-11 10:25 UTC, sipayRT commented on lib/util.js
> +exports.humanizeDuration = (duration) => {
разве momentjs не умеет такое? я вроде у него видел метод `humanize`

2017-01-11 10:25 UTC, sipayRT commented on lib/reporters/flat.js
> +            broStat.failed ? chalk.red('failed') : chalk.green('passed'),
давай это тоже вынесем отсюда

2017-01-11 10:25 UTC, sipayRT commented on test/lib/reporters/flat.js
> +            assert.include(console.info.firstCall.args[0], `16 min 27 sec`);
бля) ну прям не тест, а магия :) давай ты в функции для все выставишь 0, а в тестах будешь явно указывать то, что будешь проверять

2017-01-11 10:25 UTC, sipayRT commented on test/lib/reporters/flat.js
> +        });
не, это ты так будешь проверять работу внешнего модуля

2017-01-11 10:25 UTC, sipayRT commented on test/lib/reporters/html.js
> +        duration: 987654
и тут magic

2017-01-11 10:25 UTC, sipayRT commented on test/lib/reporters/html.js
> +        assert.include(html, '</html>');
раз уж ты решил проверять всю обвязку, то ты пропустил открывающий тег. Я поэтому и спросил про либу, которая сама седлала бы обвязку - нам бы не пришлось это тестировать

2017-01-11 10:25 UTC, sipayRT commented on test/lib/reporters/html.js
> +        it('"passed" tests status if browser statistic has not failed tests', () => {
not --> no

2017-01-11 10:25 UTC, sipayRT commented on test/lib/reporters/html.js
> +            assert.include(html, '<td>failed</td>');
в описании хочешь проверить "passed", а по коду проверил поле "failed"

2017-01-11 12:07 UTC, sipayRT commented on lib/reporters/html.js
> +        /*eslint-disable */
кстати, лучше дизейблить определенное правило, а не все сразу

2017-01-11 17:39 UTC, tormozz48 commented on lib/reporters/html.js
> +            broStat.duration = util.humanizeDuration(broStat.duration);
> давай "человеческое" время записывать сразу при вычислении времени прохождения, чтобы потом в каждом репортере не выполнять одну и ту же информацию

Не согласен. Это view - преобразование. Оно не должно храниться в модели

2017-01-11 17:40 UTC, tormozz48 commented on lib/reporters/html.js
> +        header: _.keys(columns),
> или это для того, чтобы была четкая последовательность? 

да

2017-01-11 17:43 UTC, tormozz48 commented on lib/util.js
> +        fs.writeFileSync(fileFullPath, content, {encoding: 'utf-8'});
> А почему не асинхронно?

Асинхронность нужна когда у тебя есть много конкурентных операций ввода-вывода, например при работе сервера или сборщика какого-либо. Здесь всего 2 файловых операции.

2017-01-11 17:48 UTC, tormozz48 commented on test/lib/reporters/flat.js
> +        sandbox.stub(console, 'info');
> давай может, чтобы не стабать console - создадим в util.js logger, по типу как это у нас сделано в gemini?

Я не вижу проблемы в том чтобы стабать `console.info`.

2017-01-11 17:49 UTC, tormozz48 commented on lib/util.js
> +exports.humanizeDuration = (duration) => {
> humanizeDuration -> stringifyDuration?)

Тогда уж лучше `formatDuration`

2017-01-11 18:09 UTC, tormozz48 commented on lib/reporters/flat.js
> +            broStat.failed ? chalk.red('failed') : chalk.green('passed'),
зачем?

2017-01-11 18:09 UTC, tormozz48 commented on lib/reporters/html.js
> +            broStat.duration = util.humanizeDuration(broStat.duration);
> давай "человеческое" время записывать сразу при вычислении времени прохождения, чтобы потом в каждом репортере не выполнять одну и ту же информацию

Нет, это плохая идея, так как форматирование времени - это view преобразование

2017-01-11 18:09 UTC, tormozz48 commented on lib/reporters/html.js
> +    return `<!DOCTYPE html>
> мож в одну строку? тут же обвязка не важна. Ну или массивом строк - у тебя их там не больше пяти должно получиться

А мне кажется, что так более наглядно

2017-01-11 21:21 UTC, tormozz48 commented on test/lib/reporters/html.js
> +        });
Исправил

2017-01-11 21:21 UTC, tormozz48 commented on test/lib/reporters/html.js
> +            assert.include(html, '<td>failed</td>');
исправил

2017-01-13 06:03 UTC, DudaGod commented on lib/reporters/util.js
> +        fs.writeFileSync(fileFullPath, content, {encoding: 'utf-8'});
а почему ты тут не захотел асинхронно файл записывать?

2017-01-13 06:06 UTC, DudaGod commented on test/lib/reporters/html.js
> +                generateStatData(),
а почему тебе не понравилось тут явно указывать failed: 0? Так на самом деле чуть легче читается и не нужно скролить вверх к хелперу.

2017-01-13 06:13 UTC, DudaGod commented on lib/reporters/util.js
> +exports.humanizeDuration = (duration) => duration ? moment(duration).format('mm:ss') : 'n/a';
если тесты будут идти больше часа то посчитает не правильно =)
хотя по идеи они столько не должны идти

2017-01-13 06:16 UTC, DudaGod approved these changes
в остальном кажется /ok

2017-01-13 08:18 UTC, tormozz48 commented on lib/reporters/util.js
> +exports.humanizeDuration = (duration) => duration ? moment(duration).format('mm:ss') : 'n/a';
Если тесты идут больше часа, то у нас большие проблемы

2017-01-13 08:21 UTC, tormozz48 commented on lib/reporters/util.js
> +        fs.writeFileSync(fileFullPath, content, {encoding: 'utf-8'});
> Ростик уже спрашивал.

Асинхронность нужна когда у тебя есть много конкурентных операций ввода-вывода, например при работе сервера или сборщика какого-либо. Здесь всего 2 файловых операции.

Синхронные IO операции не являются каким-то абсолютным злом. В ряде случаев их применение является вполне допустимым.

2017-01-13 08:28 UTC, tormozz48 commented on test/lib/reporters/html.js
> +                generateStatData(),
Разумно

2017-01-13 11:40 UTC, eGavr approved these changes
/ok

2017-01-13 11:40 UTC, eGavr commented on lib/reporters/util.js
> +exports.humanizeDuration = (duration) => duration ? moment(duration).format('mm:ss') : 'n/a';
так а в чем проблема выводить часы и если их нет, то не выводить?

2017-01-13 11:40 UTC, eGavr commented on lib/reporters/util.js
> +        console.error(err);
тут так себе ошибка будет выводиться.

либо вообще не оборачивай в try catch и пусть будет стэктрейс, либо выводи `console.log(err.message)`

2017-01-13 11:40 UTC, eGavr commented on test/lib/reporters/flat.js
> +function generateStatData(opts) {
а че ты не хочешь хелпервы в `describe` унести?

2017-01-13 11:40 UTC, eGavr commented on test/lib/reporters/html.js
> +function generateStatData(opts) {
копипаста)

вынесем в утилиты тестов?

2017-01-13 11:40 UTC, eGavr commented on test/lib/reporters/html.js
> +}
а че не стрелочная и тоже внутри `describe` ?

2017-01-13 11:40 UTC, eGavr commented on test/lib/reporters/util.js
> +        it('should show error if error occurred on saving file', () => {
show **an** error

2017-01-13 11:40 UTC, eGavr commented on test/lib/reporters/util.js
> +        it('should return "n/a" if duration was not set', () => {
а в каких случаях такое может быть?

2017-01-13 11:45 UTC, tormozz48 commented on test/lib/reporters/util.js
> +        it('should return "n/a" if duration was not set', () => {
Может если все взрывается к ипеням

2017-01-13 11:47 UTC, tormozz48 commented on lib/reporters/util.js
> +        console.error(err);
Тут политика такая, чтобы этот плагин был железо-бетонно отказоустойчивым.
Поэтому try-catch.

С другой стороны полезно видеть что-то если произошла ошибка, поэтому `console.error`

2017-01-13 11:49 UTC, tormozz48 commented on test/lib/reporters/flat.js
> +function generateStatData(opts) {
а вот Диме больше нравится когда хелперы снаружи

2017-01-13 11:49 UTC, tormozz48 commented on test/lib/reporters/html.js
> +function generateStatData(opts) {
разумно

2017-01-13 12:22 UTC, tormozz48 commented on lib/reporters/util.js
> +exports.humanizeDuration = (duration) => duration ? moment(duration).format('mm:ss') : 'n/a';
> Если тесты идут больше часа, то у нас большие проблемы

Ты не понял. Если наши gemini и hermione тесты будут идти больше часа то нас поувольняют нафиг :)

2017-01-14 15:48 UTC, merged